### ISSUE TITLE
 Warning: Prop `className` did not match. Server: ... Client: ...

### ISSUE THREAD

**Issue by EbrahimHeydari** [hajhosein/muxt#1]
سلام آقای پویان مهر.
من چند روز پیش یه پروژه nextjs رو به همراه mui شروع کردم و به این مشکل برخوردم. قضیه اینه که هر className جدیدی رو که با ()makeStyles در mui می سازم، به درستی کار می کنه اما زمانی که یه تغییر کوچک در پروژه اعمال کنم، دچار تداخل با بقیه استایل ها میشه و پروژه به هم میریزه. توی اینترنت که گشتم به [جواب درستی نرسیدم](https://stackoverflow.com/questions/51791163/warning-prop-classname-did-not-match-when-using-styled-components-with-seman). اکثر راه حل ها برای mui به همراه styled-components بود درحالی که من از emotion استفاده می کردم. به [مقاله](https://dev.to/hajhosein/nextjs-mui-v5-tutorial-2k35#what-is-this-post-about) شما که برخوردم روی پروژم اجراش کردم اما جواب نداد. گفتم شاید مشکل از پروزه منه برای همین از starter شما استفاده کردم. در ابتدا استایل ها به درستی که می کرد:

![Screenshot (274)](https://user-images.githubusercontent.com/88607578/192690975-bab82f70-b7b8-485f-b089-e399123db38a.png)

اما وقتی که یک تغییر کوچک (حتی یک space) درون پروژه اعمال می کنم، همه چی به هم میریزه:

![Screenshot (273)](https://user-images.githubusercontent.com/88607578/192691156-f2e848e5-0fda-4691-b3fa-1c8fcd64feb0.png)

راه حل دیگه ای پیدا نکردم و خواستم از شما مشورت بگیرم. اما از اونجایی که راه ارتباطی درستی مثل ایمیل یا آیدی تلگرام از شما پیدا نکردم، در قسمت issue قضیه رو مطرح کردم.

بعد گرفتن جواب از شما قراره این issue رو پاک کنم. برای همین فارسی نوشتم 😅

**Comment by HPouyanmehr** [comment]
سلام ابراهیم جان، امیدوارم حالت خوب باشه

توی نکست چون رندر شدن سمت سرور رو هم داریم، در رابطه با استایل‌ها اتفاقی که میافته اینه که استایل ایجاد شده سمت سرور و سمت کلاینت متفاوت می‌شه اسمشون و تناقض پیش میاد برای اپ که تشخیص بده استایل درست کدومه. (البته این علت رو احتمالاً خودت میدونی و یا متوجه‌اش شدی.)

من هم توی استارترها از emotion استفاده کردم. 
برای حل هم، این مسئله رو میشه توی فایل document.jsx_ و app.jsx_ برطرفش کرد. به این صورت که یه دونه cache برای emotion ایجاد می‌کنی اول داخل docment.jsx_ و اگه وجود داشته باشه به عنوان پراپ فرستاده میشه داخل app.jsx_. استفاده ازین کش در نهایت باعث میشه که از یک کلید برای یه استایل واحد استفاده بشه و دوگانگی‌ای داخل اسم استایلات پیش‌ نیاد. برای اینکه دقیق‌تر و روی کد ماجرا رو ببینی پیشنهاد می‌کنم به دوتا مثال خود MUI برای Next.js مراجعه کن. (مثال برای [جاوااسکریپت](https://github.com/mui/material-ui/tree/master/examples/nextjs) و مثال برای [تایپ‌اسکریپت](https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript)).

اگه مراحل بالا رو رفتی یا اینکه از قبل امتحانش کرده بودی و بازم جواب نداد لطفاً یه ریپو از کدت بساز که بتونم ببینم کاری که انجام میدی رو و امکانش باشه که بهتر و دقیق‌تر کمکت کنم.

و اینکه ببخشید که بعد از چند روز دارم بهت جواب میدم، تایم آزادم خیلی کم شده و گیت‌هاب رو چند روز یک بار چک می‌کنم. اشکال نداره که سوال پرسیدی اینجا، پاکش هم نکن حالا که مطرحش کردی شاید به درد یه نفر دیگه هم خورد این گفت‌وگو. در کل ولی سوالاتت رو داخل Stackoverflow بپرسی سریع‌تر به جواب میرسی.

**Comment by EbrahimHeydari** [comment]
سلام مجدد آقای پویان مهر



من تونستم یه راه ساده تر برای رفع تداخل نامگذاری mui در Nextjs پیدا کنم:



 const useStyles *=* makeStyles({

   footer: {

     position: 'sticky',

     padding: '10px 20px'

   }

 }, {name: "Mui_Footer"})





با استفاده از خصوصیت name تونستم الگوی نامگذاری کلاس ها رو تغییر بدم:


Mui_Footer-footer

همونجور که خواستید، این issue رو پاک نمی کنم . این راه حل رو هم با منبعش می
ذارم درون issue موفق باشید.

‫‪Hosein Pouyanmehr‬‏ ***@***.***‬‏> در تاریخ پنجشنبه ۲۹
سپتامبر ۲۰۲۲ ساعت ۲۳:۱۲ نوشت:‬

**Comment by EbrahimHeydari** [comment]
After 5 hours of searching, I found [this](https://stackoverflow.com/a/68615936/15248776) solution that works for me. i hope help you

**Comment by HPouyanmehr** [comment]
Thanks for sharing this solution.

I'll close this as it was a question and not an issue related to this repo.
